### PR TITLE
Merged duplicate folders (Uppercase/Lowecase)

### PR DESCRIPTION
**Pull request by Korri**
Folders `lib/PayPal/Types/ap/` and `lib/PayPal/Types/ap/` contained almost the same files, merged them (`ap` doesn't matche the case of the NameSpace), should work fine on linux now.

### CODE REVIEW

**Comment by Luceos** [comment]
:+1:

**Comment by muratyaman** [comment]
cheers :)

**Comment by Korri** [comment]
Same thing for folders `lib/PayPal/Types/common/` and `lib/PayPal/Types/Common/`

**Comment by muratyaman** [comment]
no one is looking after this repo ?!

**Comment by jaypatel512** [comment]
Done ! Apologies that it took longer than normal to get this out. I will make new release with this fix soon.

**Comment by jaypatel512** [comment]
Released : https://github.com/paypal/adaptivepayments-sdk-php/releases/tag/v3.9.2

**Comment by jaypatel512** [comment]
Thanks @Korri for the PR.

**Pull request merged**
